1. Principal Component Analysis (PCA)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

# Sample data
data = pd.DataFrame({
    'A': [2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 2, 1, 1.5, 1.1],
    'B': [2.4, 0.7, 2.9, 2.2, 3, 2.7, 1.6, 1.1, 1.6, 0.9]
})

# Standardize the data (mean=0, variance=1)
data_standardized = (data - data.mean()) / data.std()

# Perform PCA
pca = PCA(n_components=2)
principal_components = pca.fit_transform(data_standardized)

print("Explained Variance Ratios:", pca.explained_variance_ratio_)
print("Principal Components:\n", principal_components)


Explained Variance Ratios: [0.96296464 0.03703536]
Principal Components:
 [[-1.03068029 -0.21205314]
 [ 2.19045016  0.1689423 ]
 [-1.17818776  0.47577321]
 [-0.32329464  0.16119898]
 [-2.07219947 -0.25117173]
 [-1.10117414  0.2186533 ]
 [ 0.08785251 -0.43005447]
 [ 1.40605089  0.05281009]
 [ 0.53811824  0.02021127]
 [ 1.48306451 -0.20430982]]


2. Principal Axis Factoring (PAF)

In [ ]:
pip install factor_analyzer

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 1.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for factor_analyzer: filename=factor_analyzer-0.5.1-py2.py3-none-any.whl size=42565 sha256=426b802d77188a47ed24b87368932ecba56594773b0e29c2f2e112da145c139d
  Stored in directory: /root/.cache/pip/wheels/24/59/82/6493618e30ed1cb7a013b9e1b0c9e17de80b04dfcef4ba8a4d
Successfully built factor_analyzer


In [ ]:
import pandas as pd
from factor_analyzer import FactorAnalyzer

# Sample data
data = pd.DataFrame({
    'A': [2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 2, 1, 1.5, 1.1],
    'B': [2.4, 0.7, 2.9, 2.2, 3, 2.7, 1.6, 1.1, 1.6, 0.9],
    'C': [1.1, 0.3, 1.7, 1.1, 1.5, 1.2, 1.0, 0.8, 0.6, 0.7]
})

# Standardize the data
data_standardized = (data - data.mean()) / data.std()

# Perform PAF
fa = FactorAnalyzer(n_factors=2, method='principal', rotation='varimax')
fa.fit(data_standardized)

# Loadings and variance
loadings = fa.loadings_
variance = fa.get_factor_variance()

print("Factor Loadings:\n", loadings)
print("Factor Variance:\n", variance)


Factor Loadings:
 [[0.87617461 0.46867084]
 [0.7311575  0.6547601 ]
 [0.49371108 0.86556203]]
Factor Variance:
 (array([1.54602387, 1.39756076]), array([0.51534129, 0.46585359]), array([0.51534129, 0.98119488]))


3. Maximum Likelihood Factor Analysis (MLFA)

In [ ]:
import pandas as pd
from factor_analyzer import FactorAnalyzer

# Sample data
data = pd.DataFrame({
    'A': [2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 2, 1, 1.5, 1.1],
    'B': [2.4, 0.7, 2.9, 2.2, 3, 2.7, 1.6, 1.1, 1.6, 0.9],
    'C': [1.1, 0.3, 1.7, 1.1, 1.5, 1.2, 1.0, 0.8, 0.6, 0.7]
})

# Standardize the data
data_standardized = (data - data.mean()) / data.std()

# Perform MLFA
fa = FactorAnalyzer(n_factors=2, method='ml', rotation='varimax')
fa.fit(data_standardized)

# Loadings and variance
loadings = fa.loadings_
variance = fa.get_factor_variance()

print("Factor Loadings:\n", loadings)
print("Factor Variance:\n", variance)


Factor Loadings:
 [[0.80468    0.53217683]
 [0.70239617 0.67782944]
 [0.5211135  0.80492393]]
Factor Variance:
 (array([1.41242957, 1.39056746]), array([0.47080986, 0.46352249]), array([0.47080986, 0.93433234]))
